<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20180923 19:53:07.902" generator="Robot 3.0.4 (Python 2.7.10 on darwin)">
<suite source="/Users/swapan/AutomationFramework/TestCases/tc001_verify_total_amount.txt" id="s1" name="TestCases">
<test id="s1-t1" name="TC1 Verify Total Amount">
<kw name="Launch Application" library="Common_Keywords">
<doc>Launching App http://0.0.0.0:4723/wd/hub</doc>
<arguments>
<arg>${remote_url}</arg>
</arguments>
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.</doc>
<arguments>
<arg>${remote_url}</arg>
<arg>platformName=${platformname}</arg>
<arg>deviceName=${devicename}</arg>
<arg>appPackage=${apppackage}</arg>
<arg>appActivity=${appactivity}</arg>
<arg>appwaitactivity=${appwaitactivity}</arg>
<arg>automationName=${automationname}</arg>
</arguments>
<assign>
<var>${app}</var>
</assign>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20180923 19:53:14.985" level="FAIL">No application is open</msg>
<status status="FAIL" endtime="20180923 19:53:14.985" starttime="20180923 19:53:14.982"></status>
</kw>
<msg timestamp="20180923 19:53:14.985" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20180923 19:53:14.988" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The file at path /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.8.apk does not exist or is not accessible
</msg>
<status status="FAIL" endtime="20180923 19:53:14.988" starttime="20180923 19:53:08.088"></status>
</kw>
<status status="FAIL" endtime="20180923 19:53:14.988" starttime="20180923 19:53:08.088"></status>
</kw>
<doc>Verify total amount by entering billing amount</doc>
<status status="FAIL" endtime="20180923 19:53:14.988" critical="yes" starttime="20180923 19:53:08.087">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The file at path /usr/local/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.8.apk does not exist or is not accessible
</status>
</test>
<status status="FAIL" endtime="20180923 19:53:14.989" starttime="20180923 19:53:07.906"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" id="s1" name="TestCases" pass="0">TestCases</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20180923 19:53:14.985" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
